### ISSUE TITLE
Incorrect `Recent Activity`

### ISSUE THREAD

**Issue by phoward38** [devXprite/gitglance#1]
My `Recent Activity` showed many `started repository...`, but these were not my repositories. Perhaps this is a misspelling of `starred`, but if so, these were repositories I removed from my starred list.

**Comment by devXprite** [comment]
Thanks for letting us know! You were right - we made a mistake and should have `starred` instead of `started` So sorry about that, our bad!

Repos that showed up in your recent activity were ones you starred before. But we can't tell if you un-starred them or not because of the GitHub API limitations.
